## Slicing by Numpy

In [1]:
import numpy as np

a = np.array([6,7,8,9])
a[2]

8

In [3]:
a[1:3]

array([7, 8])

In [4]:
a[0:]

array([6, 7, 8, 9])

In [5]:
a[-2]

8

In [9]:
b = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

b[1,2]

6

In [10]:
b[2][1]

8

In [11]:
b[2,0:3]

array([7, 8, 9])

In [12]:
b[-1,0:3]

array([7, 8, 9])

In [16]:
# printing the column from the table

b[:, 1:2]

array([[2],
       [5],
       [8]])

In [17]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [20]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

# horizontally concatenation not merging
h = np.hstack((c,d))
h

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [22]:
c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [24]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])

# vertically concatenation not merging
v = np.vstack((c,e))
v

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

## Horizontal and Vertical split

In [31]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])

np.hsplit(transactions, [3])

# 1st array after split
# 2nd array column split

[array([['101', 'Mohan', '250.5'],
        ['102', 'Bob', '150.0'],
        ['103', 'Fatima', '300.75'],
        ['104', 'David', '400.2'],
        ['105', 'Aryan', '330.1']], dtype='<U32'),
 array([['2023-08-01'],
        ['2023-08-02'],
        ['2023-08-01'],
        ['2023-08-03'],
        ['2023-08-04']], dtype='<U32')]

In [32]:
np.vsplit(transactions, [4])

# 1st array after reducing row
# 2nd array after reduced row

[array([['101', 'Mohan', '250.5', '2023-08-01'],
        ['102', 'Bob', '150.0', '2023-08-02'],
        ['103', 'Fatima', '300.75', '2023-08-01'],
        ['104', 'David', '400.2', '2023-08-03']], dtype='<U32'),
 array([['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')]

In [40]:
monthly_sales = np.array([30, 33, 35, 28, 42])
result = monthly_sales > 32
result

array([False,  True,  True, False,  True])

In [39]:
monthly_sales[result]

array([33, 35, 42])

In [ ]:
# maximum sales , index

In [41]:
index = np.argmax(monthly_sales)
index

4

In [42]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [48]:
transactions[:,2]

array(['250.5', '150.0', '300.75', '400.2', '330.1'], dtype='<U32')

In [51]:
t_index = np.argmax(transactions[:,2])
t_index

3

In [52]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [53]:
transactions[transactions[:,0] == '102']

array([['102', 'Bob', '150.0', '2023-08-02']], dtype='<U32')