## how many time is taken my python list or numpy list

### Python

In [3]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [4]:
import sys

singel_ele = sys.getsizeof(python_list[0])
list_size = sys.getsizeof(python_list[0])*len(python_list)

singel_ele, list_size

(28, 2800)

### Numpy

In [6]:
import numpy as np

arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
numpy_arr = np.arange(100)
numpy_arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
numpy_arr.nbytes

800

## Speed

### Python

In [13]:
l1 = [1,2,3]
l2 = [8,7,9]

tuple(zip(l1, l2))    

((1, 8), (2, 7), (3, 9))

In [14]:
for x, y in zip(l1, l2):
    print(x, y)

1 8
2 7
3 9


In [17]:
import time

Length = 1000000

l1 = list(range(Length))
l2 = list(range(Length))

start_time = time.time()
l3 = [x+y for x,y in zip(l1, l2)]
end_time = time.time()

Python_List_time = end_time - start_time
Python_List_time

0.044673919677734375

In [ ]:
### Nump

In [19]:
n1 = np.arange(Length)
n2 = np.arange(Length)

n1[:4], n2[:4]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [20]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()

print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.004185199737548828


## Built In Functions

### Python

In [3]:
l1 = list(range(5))
l2 = list(range(5))

l1[:4], l2[:4]

([0, 1, 2, 3], [0, 1, 2, 3])

In [4]:
l3 = [x+y for x,y in zip(l1, l2)]
l3

[0, 2, 4, 6, 8]

### Numpy

In [6]:
import numpy as np

n1 = np.arange(5)
n2 = np.arange(5)

n1, n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [7]:
n3 = n1 + n2
n3

array([0, 2, 4, 6, 8])