<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

Below two numpy arrays are given with following columns. 

* Employee Details (1) Employee ID (2) Department (3) Salary
* Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed

Using these two arrays you need to complete set of tasks which are given in the notebook cells (along with hints)

In [3]:
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])


array([['101', 'Sales', '55000', 'Satya Nadella', '101', '85', '5'],
       ['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['103', 'IT', '72000', 'Fatima Razaak', '103', '92', '7'],
       ['104', 'Sales', '60000', 'John Smith', '104', '88', '6'],
       ['105', 'IT', '68000', 'Priya Singh', '105', '79', '4'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['107', 'IT', '71000', 'Michael Brown', '107', '91', '8'],
       ['108', 'Sales', '59000', 'Sunita Sharma', '108', '77', '4'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U21')

### Task 1: Merge above two numpy arrays using np.hstack

In [4]:
# write code here
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])

np.hstack((employee_details,performance_metrics))

array([['101', 'Sales', '55000', 'Satya Nadella', '101', '85', '5'],
       ['102', 'HR', '52000', 'Emily Johnson', '102', '78', '3'],
       ['103', 'IT', '72000', 'Fatima Razaak', '103', '92', '7'],
       ['104', 'Sales', '60000', 'John Smith', '104', '88', '6'],
       ['105', 'IT', '68000', 'Priya Singh', '105', '79', '4'],
       ['106', 'HR', '54000', 'Li Wei', '106', '81', '5'],
       ['107', 'IT', '71000', 'Michael Brown', '107', '91', '8'],
       ['108', 'Sales', '59000', 'Sunita Sharma', '108', '77', '4'],
       ['109', 'HR', '53000', 'Chen Wei', '109', '83', '4']], dtype='<U21')

### Task 2: Print All the Salaries

In [5]:
# write code here
all_salaries = employee_details[:, 2]
all_salaries

array(['55000', '52000', '72000', '60000', '68000', '54000', '71000',
       '59000', '53000'], dtype='<U21')

### Task 3:  Print All the Salaries in Ascending Order

In [4]:
# write code here
import numpy as np

employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])
all_salaries = employee_details[:, 2]
all_salaries

salaries = np.sort(all_salaries)
salaries

array(['52000', '53000', '54000', '55000', '59000', '60000', '68000',
       '71000', '72000'], dtype='<U21')

In [5]:
all_salaries = employee_details[:, 2]
all_salaries

array(['55000', '52000', '72000', '60000', '68000', '54000', '71000',
       '59000', '53000'], dtype='<U21')

### Task 4:  Iterate through entire array and print only employee id and name

In [14]:
# write code here
for columns in employee_details:
    print(f"ID: {columns[0]}, NAME: {columns[3]}")

ID: 101, NAME: Satya Nadella
ID: 102, NAME: Emily Johnson
ID: 103, NAME: Fatima Razaak
ID: 104, NAME: John Smith
ID: 105, NAME: Priya Singh
ID: 106, NAME: Li Wei
ID: 107, NAME: Michael Brown
ID: 108, NAME: Sunita Sharma
ID: 109, NAME: Chen Wei


### Task 5: Print performance score of all the employees

In [16]:
# write code here
scores = performance_metrics[:, 1]
scores

array([85, 78, 92, 88, 79, 81, 91, 77, 83])

### Task 6: Convert these scores to float type by using astype(float) function

In [17]:
# write code here
scores.astype(float)

array([85., 78., 92., 88., 79., 81., 91., 77., 83.])

### Task 7:  Now print the average performance score of all the employees

In [19]:
# write code here
round(np.average(scores),2)

83.78

### Task 8:  Print all the unique departments. You can use np.unique function for this

In [21]:
# first print departments from all the records

departments = employee_details[:, 1]
departments

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

In [22]:
# write code here

unique_departments = np.unique(departments)
unique_departments

array(['HR', 'IT', 'Sales'], dtype='<U21')

### Task 9: Print average salary in HR department

In [6]:
# First print all the records in HR department
hr_column = employee_details[employee_details[:, 1] == 'HR']
hr_column

array([['102', 'HR', '52000', 'Emily Johnson'],
       ['106', 'HR', '54000', 'Li Wei'],
       ['109', 'HR', '53000', 'Chen Wei']], dtype='<U21')

In [12]:
# Now from these records only print  the salary column. Convert that to float using astype(float) function

# write code here
hr_salary = hr_column[:, 2].astype(float)
hr_salary

array([52000., 54000., 53000.])

In [13]:
# Take an average of this column using np.mean() function

# write code here
hr_salary_avg = np.average(hr_salary)
hr_salary_avg

53000.0