In [2]:
import numpy as np

rev_quater1 = np.array([10, 12, 9])
rev_quater1.ndim

1

In [3]:
rev = np.array([[10, 12, 9],[15, 11, 13]])
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [4]:
rev[0,0]
# accessing 1st ele of 1st array

10

In [8]:
rev = np.array([[10, 12, 9],[15, 11, 13]], dtype=np.float64)
rev.dtype

dtype('float64')

In [9]:
rev.itemsize

8

In [10]:
rev.size

6

In [11]:
rev.shape

(2, 3)

In [12]:
np.sort(rev , axis = None)

array([ 9., 10., 11., 12., 13., 15.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
# print ele at 2 space 

In [18]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [2]:
import numpy as np
np.linspace(20,30,5)

# it will print 5 ele at equal space

array([20. , 22.5, 25. , 27.5, 30. ])

In [4]:
rev = np.array([[10, 12, 9],[15, 11, 13]], dtype=np.float64)
rev.flatten()

# it will return a new array without modifiled the original sequence

array([10., 12.,  9., 15., 11., 13.])

In [5]:
rev.min() # minimum revenue

9.0

In [6]:
rev.max()

15.0

In [7]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [10]:
rev.sum(axis=0)  # doing sum by column wise (vertically)

array([25., 23., 22.])

In [9]:
rev.sum(axis=1) # doing sum of 1st row (horizontally)

array([31., 39.])

In [11]:
for row in rev:
    print("row: ", row)

row:  [10. 12.  9.]
row:  [15. 11. 13.]


In [12]:
b = np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [13]:
np.square(b)

array([  1,  16, 256])

In [14]:
np.std(b)

6.48074069840786